In [1]:
import torch
import torch.nn as nn

In [2]:
torch.device('cpu'), torch.device('mps')

(device(type='cpu'), device(type='mps'))

In [3]:
# 查询Mac是否支持mps加速
torch.backends.mps.is_available()
# 拥有cuda是 torch.cuda.is_available()

True

In [4]:
torch.backends.mps.is_macos13_or_newer

In [5]:
def get_gpu():
    if torch.has_mps == True:
        return torch.device('mps')
    return torch.device('cpu')

get_gpu()

device(type='mps')

In [6]:
x = torch.tensor([1, 2, 3])
x.device

device(type='cpu')

In [7]:
X = torch.ones((10000, 256), device=get_gpu())
X

tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]], device='mps:0')

In [8]:
Y = torch.rand(1, 256, device=get_gpu())
Y

tensor([[0.4404, 0.4217, 0.4726, 0.6862, 0.6965, 0.5534, 0.9766, 0.5027, 0.3039,
         0.8260, 0.9021, 0.1612, 0.8956, 0.7418, 0.1465, 0.9608, 0.4971, 0.4971,
         0.7647, 0.3747, 0.3643, 0.6594, 0.3533, 0.6164, 0.2622, 0.0846, 0.4041,
         0.3695, 0.1467, 0.4649, 0.3050, 0.1510, 0.1274, 0.4837, 0.7521, 0.2807,
         0.3866, 0.3326, 0.7983, 0.9178, 0.0586, 0.7754, 0.1751, 0.4494, 0.5030,
         0.0317, 0.0894, 0.7983, 0.4745, 0.6201, 0.5932, 0.2854, 0.8374, 0.9212,
         0.6672, 0.9920, 0.8630, 0.0513, 0.5349, 0.4433, 0.4852, 0.8259, 0.3185,
         0.0475, 0.4764, 0.6021, 0.5176, 0.4714, 0.9581, 0.4980, 0.0900, 0.9876,
         0.4223, 0.0098, 0.9998, 0.8665, 0.3148, 0.1312, 0.7308, 0.7441, 0.1197,
         0.4166, 0.5202, 0.3649, 0.0751, 0.8900, 0.1096, 0.8052, 0.9739, 0.2592,
         0.0543, 0.9328, 0.5642, 0.3955, 0.0053, 0.0720, 0.9721, 0.2248, 0.1500,
         0.2527, 0.0968, 0.0396, 0.0774, 0.5664, 0.4062, 0.0878, 0.1830, 0.7540,
         0.3480, 0.4695, 0.1

In [9]:
Z = X.to('mps')
Z

tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]], device='mps:0')

In [10]:
Y + Z

tensor([[1.4404, 1.4217, 1.4726,  ..., 1.9779, 1.4181, 1.9613],
        [1.4404, 1.4217, 1.4726,  ..., 1.9779, 1.4181, 1.9613],
        [1.4404, 1.4217, 1.4726,  ..., 1.9779, 1.4181, 1.9613],
        ...,
        [1.4404, 1.4217, 1.4726,  ..., 1.9779, 1.4181, 1.9613],
        [1.4404, 1.4217, 1.4726,  ..., 1.9779, 1.4181, 1.9613],
        [1.4404, 1.4217, 1.4726,  ..., 1.9779, 1.4181, 1.9613]],
       device='mps:0')

In [11]:
Z.is_mps

True

In [12]:
net = nn.Sequential(
    nn.Linear(256, 128),
    nn.Sigmoid(),
    nn.Linear(128, 64),
    nn.ReLU(),
    nn.Linear(64, 16),
    nn.Tanh(),
    nn.Linear(16, 1)
)
net = net.to(device=get_gpu())

In [13]:
X.shape

torch.Size([10000, 256])

In [14]:
net(X)

tensor([[0.0235],
        [0.0235],
        [0.0235],
        ...,
        [0.0235],
        [0.0235],
        [0.0235]], device='mps:0', grad_fn=<LinearBackward0>)

In [15]:
net[0].weight.data.device

device(type='mps', index=0)